name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
  lint:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: check codestyle
        run: npm run format:check
      - name: lint
        run: npm run lint
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: test
        run: npm test
