name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
  format:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: format
        run: npm run format
  lint:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
  test/unit:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: unit tests
        run: npm test
  test/e2e:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: install node v13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: npm install
        run: npm install
      - name: e2e tests
        run: npm test:e2e
